### ISSUE TITLE
Elevators not working

### ISSUE THREAD

**Issue by iJoeyMonster** [OpenMods/openmods.info#2]
The elevators aren't working. I've tried survival and creative. I've tried different colors (but they default to white when placed down). I've tried editing the PassThrough in the config from 4 to 20 and it didn't work. There's only 13 spaces between the blocks and 0 solid blocks. I've updated to the latest versions from the website. The rotating elevators don't work either. How do I get them to work?  Attached are screenshots of the area between the blocks.
<img width="906" alt="screenshot_3" src="https://cloud.githubusercontent.com/assets/17676227/14125597/0b9cca76-f5da-11e5-8395-7da33c8b0aba.png">
<img width="910" alt="screenshot_4" src="https://cloud.githubusercontent.com/assets/17676227/14125598/0b9cd5b6-f5da-11e5-9a68-5b1c8d25961a.png">

**Comment by boq** [comment]
Here's response from out [FAQ](openmods.info/faq.html#ob)

There are usually few possible causes:
- Not enough XP. Since few versions elevators drain experience in survival mode. This option can be disabled in configuration.
- Too many blocks between elevators. This limitation is also configurable. (_note: it's separate parameter from PassThrough_)
- Badly implemented air-like blocks. Most mods implemented various fake air, light and tracking blocks right, but there is still room for misbehaving implementation.
- ~~Different elevator colors. Elevators will only teleport to other elevators with same color.~~

**Comment by iJoeyMonster** [comment]
You didn't read the issue. XP is not the issue if it doesn't even work in creative. It was set to 0.0 in the config anyway. 
13 spaces, 0 solid blocks between them. I don't see a separate thing? 

![](http://i.imgur.com/11oqykB.png)

I don't think there are air blocks? Are there any known mods that prevent elevators from working?

**Comment by boq** [comment]
Maybe it's something like OpenMods/OpenBlocks#753? Please try apply fix I described there.

Note: this is 'openmods.info' page repo, in future please report bugs in correct projects (like one linked here).
